### ISSUE TITLE
Can't use in OS Version 10.12.4

### ISSUE THREAD

**Issue by LiShuxue** [LigeiaRowena/Resign#2]
Before i can use it well, but when i update my OS X version to 10.12.4,  it can't use.
when i user it resign my ipa, it show me Generating entitlements.., and can not go on

**Comment by LigeiaRowena** [comment]
Fixed with commit a50d4f7 commit

**Comment by LiShuxue** [comment]
i try again just now, it also show me Generating entitlements..  can't go on and can't get the ipa

**Comment by LiShuxue** [comment]
macOS Sierra   Version 10.12.4

**Comment by LigeiaRowena** [comment]
You are right, I'm sorry I forgot to build the new app: on commit 3db9e50 you can find it.

**Comment by LiShuxue** [comment]
every thing goes well, thank you very much !
